AWSTemplateFormatVersion: '2010-09-09-OC'
Description: Default organization blueprint

# https://aws.amazon.com/blogs/mt/best-practices-for-organizational-units-with-aws-organizations/
Organization:

  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: 'Bowo'
      RootEmail: ayodejisadiku@gmail.com
      AccountName: Management Account
      AccountId: '847408437196'
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: ayodejisadiku@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      DefaultBuildAccessRoleName: OrganizationFormationBuildAccessRole

  # Organizational Unit used for Production workloads
  ProdOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Production
      Accounts: []

  # Organizational Unit used for the Development team
  SdlcOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Test
      Accounts: []

  